relief_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView # used for logout
# to direct javascript to the correct url
from django.contrib.auth.views import LogoutView, PasswordResetDoneView, PasswordResetCompleteView # used for logout

#from accounts.views import CustomLogoutView as CustomLogoutView__  # Adjust the import according to your file structure
from accounts import views as accounts_views
from analytics import views as analytics_views
from communication import views as communication_views
from feedback import views as feedback_views
from matching import views as matching_views
from offers import views as offers_views
from requests_app import views as requests_views
from main import views as main_views


urlpatterns = [
    # main views
    #path("",main_views.base, name='base'),# took this away as we was want the home page to be the main page
    path("", main_views.home, name='home'),
    path('about_us/', main_views.about_us, name='about_us'),
    path('faq/', main_views.faq, name='faq'),
    path('contact/', main_views.contact, name='contact'),

    # accounts views
    path('logout/', accounts_views.user_logout, name='logout'),
    path('signup/', accounts_views.signup, name='signup'),
    path('profile/edit/', accounts_views.profile_edit, name='profile_edit'),
    path('profile/', accounts_views.profile_view, name='profile_view'),
    path('login/', accounts_views.user_login, name='login'),
    

    #Reset password
    path('reset_password/', accounts_views.CustomPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_done/', PasswordResetDoneView.as_view(template_name='reset_password_done.html'), name='reset_password_done'),
    path('reset/<uidb64>/<token>/', accounts_views.CustomPasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'), name='reset_password_complete'),
    #path('password_reset_email/', accounts_views.password_reset_email, name='password_reset_email'),
   
    # analytics views
    path('dashboard/', analytics_views.dashboard, name='dashboard'),

    # communication views
    path('inbox/', communication_views.inbox, name='inbox'),
    path('send/', communication_views.send_message, name='send_message'),
    path('view_message/<int:message_id>/', communication_views.view_message, name='view_message'),
    path('send/<int:recipient_id>/', communication_views.send_message, name='send_message_to'),
    path('delete_message/<message_id>/', communication_views.delete_message, name='delete_message'),
    
    
    
    # feedback views
    path('give_feedback/', feedback_views.give_feedback, name='give_feedback'),
    path('list_feedback/', feedback_views.feedback_list, name='feedback_list'),

    # matching views
    path('matches/', matching_views.view_matches, name='view_matches'),

    # offers views (for donors)
    path('create_offer/', offers_views.create_offer, name='create_offer'),# changed
    path('user_offer_list/', offers_views.user_offer_list, name='user_offer_list'),# look at their own offers
    path('edit_offer/<int:pk>/', offers_views.edit_offer, name='edit_offer'), # changed
    path('delete_offer/<int:pk>/', offers_views.delete_offer, name='delete_offer'), # changed
    path('user_offer_details/<int:pk>/', offers_views.user_offer_details, name='user_offer_details'),
    #path('view_requests_and_accept/', offers_views.offer_view_requests, {'page_type': 'all'}, name='view_requests_and_accept'),
    #path('view_accepted_requests/', offers_views.offer_view_requests, {'page_type': 'accepted'}, name='view_accepted_requests'),
    path('view_requests_and_accept/', offers_views.view_requests_and_accept, name='view_requests_and_accept'),
    path('view_accepted_requests/', offers_views.view_accepted_requests, name='view_accepted_requests'),
    path('offers_view_requester_detail/<int:request_id>/', offers_views.offers_view_requester_detail, name='offers_view_requester_detail'),
    path('toggle_accept/', offers_views.toggle_accept, name='toggle_accept'),
    

    
    # requests views (for beneficiaries)
    path('create_request/', requests_views.create_request, name='create_request'),
    path('user_request_list/', requests_views.user_request_list, name='user_request_list'),
    path('edit_request/<int:pk>/', requests_views.edit_request, name='edit_request'),
    path('delete_request/<int:pk>/', requests_views.delete_request, name='delete_request'),
    path('user_request_details/<int:pk>/', requests_views.user_request_details, name='user_request_details'),
    
    path('requester_view_offers/', requests_views.requester_view_offers, name='requester_view_offers'),
    path('requester_view_offers_detail/<int:offer_id>/', requests_views.requester_view_offers_detail, name='requester_view_offers_detail'),
    path('requester_liked_offers/', requests_views.requester_liked_offers, name='requester_liked_offers'),
    path('toggle_like/', requests_views.toggle_like, name='toggle_like'),
    
    #path('cancel_request/<int:pk>/', requests_views.request_cancel, name='request_cancel'),# changed
    #path('search_requests/', requests_views.search_requests, name='search_requests'),

    #path('base/', TemplateView.as_view(template_name='base.html'), name='base'),# I've created this maybe wrong
    #base help support home    
]

requests_app/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone

class Request(models.Model):
    CATEGORY_CHOICES = (
        ('food', 'Food'),
        ('water', 'Water'),
        ('clothing', 'Clothing'),
        ('shelter', 'Shelter'),
        ('medical', 'Medical Supplies'),
        ('other', 'Other'),
    )
    URGENCY_LEVELS = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    )
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    )
    LOCATION_CHOICES = (
        ('address', 'Address'),
        ('coordinates', 'Latitude and Longitude'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='No title given')
    description = models.TextField(default='No description given')
    location_type = models.CharField(max_length=20, choices=LOCATION_CHOICES, default='address')
    address = models.CharField(
        max_length=255,
        blank=True,
        default="No address provided"
    )
    latitude = models.FloatField(
        null=True,
        blank=True,
        default=51.99656842422461
    )
    longitude = models.FloatField(
        null=True,
        blank=True,
        default=-0.9913942306871908
    )
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='Other')
    urgency = models.CharField(max_length=10, choices=URGENCY_LEVELS, default='Low')
    status = models.CharField(max_length=11, choices=STATUS_CHOICES, default='Pending')
    accepted_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='accepted_requests'
    )
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.title

requests_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Request
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderServiceError

class RequestForm(forms.ModelForm):
    LOCATION_CHOICES = [
        ('address', 'Address'),
        ('coordinates', 'Latitude and Longitude'),
    ]

    location_type = forms.ChoiceField(
        choices=LOCATION_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Location Type',
        help_text='Select how you would like to provide your location.'
    )

    class Meta:
        model = Request
        fields = [
            'title',
            'description',
            'location_type',
            'address',
            'latitude',
            'longitude',
            'category',
            'urgency',
            'status'
        ]
        help_texts = {
            'address': 'Enter your address.',
            'latitude': 'Enter your latitude coordinate.',
            'longitude': 'Enter your longitude coordinate.',
        }
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'urgency': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'longitude': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)

        # made the location_type field required to prevent errors of not selecting a location type
        if self.instance and self.instance.location_type:
            self.fields['location_type'].initial = self.instance.location_type

    def clean(self):
        cleaned_data = super().clean()
        location_type = cleaned_data.get('location_type')
        address = cleaned_data.get('address')
        latitude = cleaned_data.get('latitude')
        longitude = cleaned_data.get('longitude')

        if location_type == 'address':
            if not address or address.strip() == '' or address == "No address provided":
                self.add_error('address', "Please provide an address.")
            else:
                # check the Geocoding service to see if the address is valid
                geolocator = Nominatim(user_agent="your_app_name")  # Replace with your app's name
                try:
                    location = geolocator.geocode(address, timeout=10)
                    if location is None:
                        self.add_error('address', "Please provide a valid address.")
                    else:
                        # not using the location data
                        # cleaned_data['latitude'] = location.latitude
                        # cleaned_data['longitude'] = location.longitude
                        pass
                except GeocoderServiceError:
                    self.add_error('address', "Geocoding service error. Please try again later.")
                except Exception as e:
                    self.add_error('address', "An error occurred while validating the address.")
            # latitude and longitude cleared
            cleaned_data['latitude'] = None
            cleaned_data['longitude'] = None
        elif location_type == 'coordinates':
            if latitude is None or longitude is None:
                if latitude is None:
                    self.add_error('latitude', "Please provide latitude.")
                if longitude is None:
                    self.add_error('longitude', "Please provide longitude.")
            else:
                # ensure that the latitude and longitude are within the valid range
                if not (-90 <= latitude <= 90):
                    self.add_error('latitude', 'Latitude must be between -90 and 90.')
                if not (-180 <= longitude <= 180):
                    self.add_error('longitude', 'Longitude must be between -180 and 180.')
            cleaned_data['address'] = "No address provided"
        else:
            raise ValidationError("Invalid location type selected.")

        return cleaned_data

requests_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .forms import RequestForm
from .models import Request
#from django.contrib import messages
from django.http import JsonResponse

@login_required
def create_request(request):
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            # create a new request object but do not save it yet
            new_request = form.save(commit=False)
            # set the user of the request object to the current user
            new_request.user = request.user
            new_request.save()
            # redirect to the user_request_list view after creating the request
            return redirect('user_request_list')
    else:
        form = RequestForm()  

    return render(request, 'create_request.html', {'form': form})

@login_required
def user_request_list(request):
    req = Request.objects.filter(user=request.user)
    return render(request, 'user_request_list.html', {'requests_app': req})

@login_required
def user_request_details(request, pk):
    req = get_object_or_404(Request, pk=pk)
    return render(request, 'user_request_details.html', {'request_': req})

@login_required
def edit_request(request, pk):
    req = get_object_or_404(Request, pk=pk, user=request.user)
    if request.method == 'POST':
        form = RequestForm(request.POST, instance=req)
        if form.is_valid():
            form.save()
            return redirect('user_request_list')
    else:
        form = RequestForm(instance=req)
    return render(request, 'edit_request.html', {'form': form})

@login_required
def delete_request(request, pk):
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        req = get_object_or_404(Request, pk=pk, user=request.user)
        req.delete()
        return JsonResponse({"status": "success", "message": "Request deleted successfully."})
    return JsonResponse({"status": "error", "message": "Invalid request."}, status=400)


# This is to allow requesers to view offers and like/ save what they have seen
from offers.models import Offer

@login_required
def requester_view_offers_detail(request, offer_id):
    offer = get_object_or_404(Offer, pk=offer_id)
    return render(request, 'requester_view_offers_detail.html', {'offer': offer})

@login_required
def requester_view_offers(request):
    offers = Offer.objects.all()
    return render(request, 'requester_view_offers.html', {'offers': offers})

@login_required
@login_required
def requester_liked_offers(request):
    offers = Offer.objects.filter(likes=request.user)
    return render(request, 'requester_liked_offers.html', {'offers': offers})

@login_required
def toggle_like(request):
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        offer_id = request.POST.get('offer_id')
        offer = get_object_or_404(Offer, id=offer_id)
        liked = request.user in offer.likes.all()

        if liked:
            offer.likes.remove(request.user)
        else:
            offer.likes.add(request.user)
        
        return JsonResponse({
            'status': 'success',
            'liked': not liked,
            'likes_count': offer.likes.count()
        })

    return JsonResponse({
        'status': 'error',
        'error': 'Invalid request or not an AJAX request'
    }, status=400)

requests_app/templates/create_request.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">  
<div class="container mt-4">
    <h2>Create a New Request</h2>
    <form method="post" class="request-form">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form %}
            <div class="mb-3 form-group" id="div_id_{{ field.name }}">
                {{ field.label_tag }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text }}</div>
                {% endif %}
                {{ field }}
                {% for error in field.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit Request</button>
    </form>
</div>

<!-- map validation javascript-->
<script src="{% static 'js/create_edit_map_validate.js' %}"></script>
{% endblock %}

requests_app/templates/edit_request.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"> 
<div class="container mt-4">
    <h2>Edit Request: {{ form.instance.title }}</h2>
    <form method="post" class="request-form">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form %}
            <div class="mb-3 form-group" id="div_id_{{ field.name }}">
                {{ field.label_tag }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text }}</div>
                {% endif %}
                {{ field }}
                {% for error in field.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>

<!-- Map validation Javascript -->
<script src="{% static 'js/create_edit_map_validate.js' %}"></script>
{% endblock %}

requests_app/templates/requester_view_offers_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<!-- CSS for the map -->
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

<div class="container mt-8" data-page-type="requester_view_detail_offers">
    <h2 class="text-center mb-3"><br>Offer Details</br></h2>
    <div class="row offer-container">
        <!-- Left column Offer Details -->
        <div class="col-md-12 col-lg-6 mb-4 item_offer" id="offer-{{ offer.id }}">
            <div class="card">
                <div class="card-header text-center">
                    <h3>{{ offer.title }}</h3>
                </div>
                <div class="card-body">
                    <p class="card-text"><i class="fas fa-align-left"></i> <strong>Description:</strong> {{ offer.description }}</p>
                    <p class="card-text"><i class="fas fa-map-marker-alt"></i> <strong>Location:</strong>
                        {% if offer.location_type == 'address' %}
                            {{ offer.address }}
                        {% elif offer.location_type == 'coordinates' %}
                            Latitude: {{ offer.latitude }}, Longitude: {{ offer.longitude }}
                        {% else %}
                            Location not provided
                        {% endif %}
                    </p>
                    <p class="card-text"><i class="fas fa-filter"></i> <strong>Category:</strong> {{ offer.category }}</p>
                    <p class="card-text"><i class="fas fa-info-circle"></i> <strong>Status:</strong> {{ offer.get_status_display }}</p>
                    <p class="card-text"><i class="fas fa-cubes"></i> <strong>Quantity:</strong> {{ offer.quantity }}</p>
                    <p class="card-text"><i class="fas fa-calendar-alt"></i> <strong>Availability:</strong> {{ offer.availability_start|date:"SHORT_DATE_FORMAT" }} - {{ offer.availability_end|date:"SHORT_DATE_FORMAT" }}</p>
                    <p class="card-text"><i class="fas fa-user"></i> <strong>Posted by:</strong> {{ offer.user.username }}</p>
                </div>
                <div class="card-footer bg-transparent d-flex justify-content-between">
                    <div class="d-flex justify-content-start">
                        <a href="{% url 'send_message_to' offer.user.id %}" class="btn btn-primary">
                            <i class="fas fa-envelope"></i> Message
                        </a>
                    </div>
                    <div class="d-flex justify-content-end">
                        <form method="post" class="like-form" data-offer-id="{{ offer.id }}">
                            {% csrf_token %}
                            <button type="button" class="btn {% if request.user in offer.likes.all %}btn-success{% else %}btn-outline-success{% endif %} like-btn">
                                {% if request.user in offer.likes.all %}
                                <i class="fas fa-heart"></i> Unlike
                                {% else %}
                                <i class="far fa-heart"></i> Like
                                {% endif %}
                            </button>
                            <span class="likes-count">{{ offer.likes.count }}</span>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- right column map -->
        <div class="col-md-12 col-lg-6">
            <!-- map container -->
            <div id="map"
                 data-location-type="{{ offer.location_type }}"
                 data-address="{{ offer.address|escapejs }}"
                 data-latitude="{{ offer.latitude|default_if_none:"" }}"
                 data-longitude="{{ offer.longitude|default_if_none:"" }}"
                 style="height:100%;width:100%;">
            </div>
        </div>
    </div>
    <hr>
    <a href="{{ request.META.HTTP_REFERER|escape }}">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Return</button>
    </a>
</div>

<!-- for the map -->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

<!-- for map initialization -->
<script src="{% static 'js/map_initialization_script.js' %}"></script>

<!--like functionality script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/liked_offers.js' %}"></script>
{% endblock %}

requests_app/templates/search_requests.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Search Requests</h2>
<form method="get">
    {{ filter.form|crispy }}
    <button type="submit">Search</button>
</form>
<ul>
    {% for request in filter.qs %}
    <li>
        <strong>{{ request.category }}</strong> - {{ request.description }} - {{ request.get_urgency_display }}
        <a href="{% url 'request_detail' request.pk %}">View Details</a>
    </li>
    {% empty %}
    <li>No matching requests found.</li>
    {% endfor %}
</ul>
{% endblock %}

requests_app/templates/user_request_details.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<!-- CSS for the map -->
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

<div class="container mt-8" data-page-type="user_request_details_page">
    <h2 class="text-center mb-3"><br>Request Details</br></h2>
    <div class="row request-container">
        <!-- Left column - request details -->
        <div class="col-md-12 col-lg-6 mb-4 item_request" id="request_-{{ request_.id }}">
            <div class="card">
                <div class="card-header text-center">
                    <h3>{{ request_.title }}</h3>
                </div>
                <div class="card-body">
                    <p class="card-text"><i class="fas fa-align-left"></i> <strong>Description:</strong> {{ request_.description }}</p>
                    <p class="card-text"><i class="fas fa-map-marker-alt"></i> <strong>Location:</strong>
                        {% if request_.location_type == 'address' %}
                            {{ request_.address }}
                        {% elif request_.location_type == 'coordinates' %}
                            Latitude: {{ request_.latitude }}, Longitude: {{ request_.longitude }}
                        {% else %}
                            Location not provided
                        {% endif %}
                    </p>                    
                    <p class="card-text"><i class="fas fa-filter"></i> <strong>Category:</strong> {{ request_.category }}</p>
                    <p class="card-text"><i class="fas fa-bolt"></i> <strong>Urgency:</strong> {{ request_.get_urgency_display }}</p>
                    <p class="card-text"><i class="fas fa-info-circle"></i> <strong>Status:</strong> {{ request_.get_status_display }}</p>
                    <p class="card-text"><i class="fas fa-calendar-alt"></i> <strong>Submitted on:</strong> {{ request_.created_at|date:"SHORT_DATE_FORMAT" }}</p>
                    {% if request_.accepted_by %}
                    <p class="card-text"><i class="fas fa-user-check"></i> <strong>Accepted by:</strong> {{ request_.accepted_by.username }}</p>
                    {% endif %}
                </div>
                <div class="card-footer bg-transparent d-flex justify-content-between">
                    <div class="d-flex justify-content-start">
                        {% if not request_.accepted_by %}
                        <a href="{% url 'edit_request' request_.pk %}" class="btn btn-secondary mr-2">
                            <i class="fas fa-edit"></i> Edit
                        </a>
                        {% endif %}
                    </div>
                    <div class="d-flex justify-content-end">
                        <form class="delete-form" data-request-id="{{ request_.id }}">
                            {% csrf_token %}
                            <input type="hidden" name="request_id" value="{{ request_.id }}">
                            <button type="button" class="btn btn-danger delete-btn" data-action="request">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12 col-lg-6">
            <div id="map"
                 data-location-type="{{ request_.location_type }}"
                 data-address="{{ request_.address|escapejs }}"
                 data-latitude="{{ request_.latitude|default_if_none:"" }}"
                 data-longitude="{{ request_.longitude|default_if_none:"" }}"
                 style="height:100%;width:100%;">
            </div>
        </div>
    </div>
    <hr>
    <a href="{{ request.META.HTTP_REFERER|escape }}">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Return</button>
    </a>
</div>

<!-- the map loding functions-->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="{% static 'js/map_initialization_script.js' %}"></script>

<!-- the delete offer functionality-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/request_or_offer_delete.js' %}"></script>

{% endblock %}

requests_app/templates/user_request_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<div class="container mt-4" data-page-type="user_requst_list_page">
    <h2 class="text-center mb-3">Your Requests</h2>
    <div class="row request-container">
        {% for request_ in requests_app %}
            <div class="col-md-6 col-lg-6 mb-4 item_request" id="request_-{{ request_.id }}">
                <div class="card">
                    {#<div class="card">#}
                    <div class="card-header text-center">
                        <h3>{{ request_.title }}</h3>
                    </div>
                    <div class="card-body">
                        {#<p class="card-text"><i class="fas fa-align-left"></i> <strong>Description:</strong> {{ request_.description }}</p>#}
                        {#<p class="card-text"><i class="fas fa-map-marker-alt"></i> <strong>Location:</strong> {{ request_.location }}</p>#}
                        <p class="card-text"><i class="fas fa-map-marker-alt"></i> <strong>Location:</strong>
                            {% if request_.location_type == 'address' %}
                                {{ request_.address }}
                            {% elif request_.location_type == 'coordinates' %}
                                Latitude: {{ request_.latitude }}, Longitude: {{ request_.longitude }}
                            {% else %}
                                Location not provided
                            {% endif %}
                        </p>                        
                        <p class="card-text"><i class="fas fa-filter"></i> <strong>Category:</strong> {{ request_.category }}</p>
                        <p class="card-text"><i class="fas fa-bolt"></i> <strong>Urgency:</strong> {{ request_.get_urgency_display }}</p>
                        <p class="card-text"><i class="fas fa-info-circle"></i> <strong>Status:</strong> {{ request_.get_status_display }}</p>
                        <p class="card-text"><i class="fas fa-calendar-alt"></i> <strong>Submitted on:</strong> {{ request_.created_at|date:"SHORT_DATE_FORMAT" }}</p>
                        {% if request_.accepted_by %}
                        <p class="card-text"><i class="fas fa-user-check"></i> <strong>Accepted by:</strong> {{ request_.accepted_by.username }}</p>
                        {% endif %}
                    </div>
                    <div class="card-footer bg-transparent d-flex justify-content-between">
                        <div class="d-flex justify-content-between align-items-left ">
                            {% if not request_.accepted_by %}
                            <a href="{% url 'edit_request' request_.pk %}" class="btn btn-secondary mr-2">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            {% endif %}
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'user_request_details' request_.pk %}" class="btn btn-primary">
                                <i class="fas fa-info-circle"></i> Details
                            </a>
                        </div>
                        <div class="d-flex justify-content-between align-items-right ">
                            <form class="delete-form" data-request-id="{{ request_.id }}" >
                                {% csrf_token %}
                                <input type="hidden" name="request_id" value="{{ request_.id }}">
                                <button type="button" class="btn btn-danger delete-btn" data-action="request">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class="col-12 no-requests-message">
            <div class="alert alert-info text-center">No requests found.</div>
        </div>
        {% endfor %} 
    </div>
    <hr>
    <a href="{% url 'create_request' %}"><button type="button2" class="btn btn-secondary btn-lg btn-block">Create New Request</button></a>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% load static %}
<script src="{% static 'js/request_or_offer_delete.js' %}"></script>
{% endblock %}